### ISSUE TITLE
Add content security policy middleware

### ISSUE THREAD

**Issue by JoeChapman** [UKHomeOfficeForms/hof-bootstrap#105]
Use helmet csp to implement a content security policy that whitelists origins we deem to be safe for loading assets.

Our templates inherit from https://github.com/alphagov/govuk_template/blob/master/source/views/layouts/govuk_template.html.erb which includes two script tags. As such our CSP will need to include a directive that lets inline scripts be included...
E.g. Using Helmet csp: `scriptSrc: ["'self'", "'unsafe-inline'"]`

This issue https://github.com/alphagov/govuk_template/issues/258 identifies a solution to the issue.

This PR should avoid the need to add the unsafe-inline directive: https://github.com/alphagov/govuk_template/pull/268

**Comment by davbo** [comment]
Hi @JoeChapman it's great to see you contributing to improve `govuk_template`'s CSP support.

When we deployed [CSP on Verify](https://github.com/alphagov/verify-frontend/blob/master/config/application.rb#L38-L52) we used hashes as recommended by @robinwhittleton as these rarely change. It would be good to hear why this wouldn't work for you?

CSP is moving quite quickly, on one side the [spec](https://www.w3.org/TR/CSP/#strict-dynamic-usage) and [Google](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/45542.pdf) seem to be suggesting nonce-based policies are best as they allow for easier adoption of CSP (which I generally agree with) but at the same time people are finding many ways of [bypassing nonce-based policies](http://sebastian-lekies.de/csp/bypasses.php). 

Again I'm not opposed to adding nonce support but would like to know why the hashes wouldn't work for you before we do that.

Thanks!
