### ISSUE TITLE
Licensing HO guidance is MIT but we have GPL and ISC

### ISSUE THREAD

**Issue by sulthan-ahmed** [UKHomeOfficeForms/hof-bootstrap#83]
The guidance from the central team is that our licenses in the Home Office are meant to be MIT https://github.com/UKHomeOffice/central-devteam-board/wiki#licencing.  I noticed the HOF-bootstrap is GPL-3.0 and the example is ISC.  Is HOF licensing meant to move away from the Home Office guidelines?

**Comment by joefitter** [comment]
AFAIK this only changed recently (or we were only informed of the change recently) - this repo and probably most others will likely still have GPL-3.0.

Whoever picks this up should do a sweep across all HOF components and update where applic

**Comment by easternbloc** [comment]
What @joefitter said. MIT is a new thing when this was all set up it was GPL. We should do a mass migration when possible.

**Comment by sulthan-ahmed** [comment]
No worries 👍 How do you guys pick up these things? I'm happy to volunteer but I'm guessing there is a priority of stuff to do

**Comment by joefitter** [comment]
nah, knock yourself out I'd say!

**Comment by sulthan-ahmed** [comment]
ok, I'm on it.  Thanks.

**Comment by JoeChapman** [comment]
done https://github.com/UKHomeOfficeForms/hof-bootstrap/blob/master/package.json#L5

**Comment by sulthan-ahmed** [comment]
yep 👍
