### ISSUE TITLE
Example has implicit dependency of 'hof-controllers'

### ISSUE THREAD

**Issue by chrisns** [UKHomeOfficeForms/hof-bootstrap#90]
https://github.com/UKHomeOfficeForms/hof-bootstrap/blob/master/example/apps/example-app/index.js#L3

hof-controllers should be in https://github.com/UKHomeOfficeForms/hof-bootstrap/blob/master/example/package.json

**Comment by JoeChapman** [comment]
It does: https://github.com/UKHomeOfficeForms/hof-bootstrap/blob/master/package.json

**Comment by chrisns** [comment]
but the example/package.json doesn't, it coincidently works in node 6 because of its flat dependencies

**Comment by JoeChapman** [comment]
fair

**Comment by joefitter** [comment]
Good spot @chrisns - will update.  Just as a note though - HOF only works with npm>=3 due to a bug down the line in frontend toolkit so there will always be a flat directory structure (al least until this is fixed)

**Comment by chrisns** [comment]
@joefitter it'd be coincidently there but potentially not the version you're expecting :)

**Comment by joefitter** [comment]
I know - it needs to be added, I was just pointing out as a side note we aren't able to use npm<3, more as a reminder to myself that there is an issue that should be fixed!
